// Author : Kyle Ray
// Date : 01/28/26
// Project : The goal of this exercise is to program a Guess My Number Game.

import java.util.Random; // Imports Random class so you can generate random numbers.
import java.util.Scanner; // import the Scanner module.

public class GuessStarter {
    public static void main(String[] args) {
        //Variable Define
        int delta;

        // Scanner Code
        int numberIn; // Declare a variable
        Scanner in = new Scanner(System.in); // Declare and assign Scanner

        //Random Generator Code
    Random random = new Random(); // Creates a new Random object and stores it in a variable random
        // Random random --> I'm making a variable called random that is of type Random
        // new Random() --> Actually creates the random-number generator.
                                    //
        int number = random.nextInt(100) + 1; // This line generates a random number and stores it in number
        // int number --> creates an integer variable named number.
        // random.nextInt(100) --> generates a random integer from 0 up to 99 (100 possible values)
        // +1 --> shifts that range up by 1, so now it becomes 1 up to 100

        // Final result --> number will be a random integer between 1 and 100'

        //End Random Generator Code


        //Print Out Code

        System.out.println("I'm thinking of a number between 1 and 100\n(including both). Can you guess what it is?");

        //prompt user and get the value
        System.out.print("Type a number: "); // Prompt User a Question
        numberIn = in.nextInt(); // Assign the user input to the variable. in ,means read the keyboard. nextDouble id a
        // method that waits for the user to type something, reads what is typed, converts it into
        // a double number and then gives the number back to my program.
        // Pretty much this is asking the user to type a number, read it, and store it in cm

        System.out.println("Your guess is : " + numberIn); // Prints out the number chosen by the user
        System.out.println("The number I was thinking of is : " + number); // Prints out the number chosen by the Random
        delta = Math.abs(numberIn-number); // defines the delta between the number chosen by the user and the number
                                            // generated by the program. Math.abs() gets the absolute value
        System.out.println("You were off by : " + delta); // Prints out the delta
    }
}
